### PR TITLE
Fix bundle submission missing info, empty answer handling, and multiple choice penalty calculation

### LINKED ISSUE #130: Uriel bundle submissions endpoint missing some info and grading empty answers as WA
**Bundle submission summary endpoint**
- Add placeholders for items with no answers
- Include item numbers
- Sort item submissions by item number, sort problems by alias
- Include the viewed user's basic profile

**Submit answer endpoint**
- Fix handling of empty answers (when the contestant had answered before) to return a score of 0 instead of giving a penalty (currently empty answers are given a WA verdict).

### PR DESCRIPTION
**Pull request by nathanchrs**
Fixes #130 and #135.

- Fix handling of empty answers (when the contestant had answered before) to return a score of 0 instead of giving a penalty (currently empty answers are given a WA verdict).
- Include item numbers
- Sort item answer summary entries by problem alias and item number
- Add placeholder entries (with empty answer) for items with no answers in answer summary endpoint
- Include user's basic profile in answer summary endpoint
- Fix `MultipleChoiceItemGrader` handling of penalty scores (Sandalphon uses negative values for penalty, this fix makes Uriel follow Sandalphon convention)
- Add tests for item submission endpoints
- Create `ProblemClient` class in `sandalphon-client` to abstract access to Sandalphon

### CODE REVIEW

File: judgels-backends/uriel/uriel-api/src/main/java/judgels/uriel/api/contest/submission/bundle/ContestantAnswerSummaryResponse.java [hunk 1]
```diff
@@ -0,0 +1,22 @@
...
+import java.util.Map;
+import judgels.jophiel.api.profile.BasicProfile;
+import judgels.sandalphon.api.submission.bundle.ItemSubmission;
+import judgels.uriel.api.contest.submission.ContestSubmissionConfig;
+import org.immutables.value.Value;
+
+@Value.Immutable
+@JsonDeserialize(as = ImmutableContestantAnswerSummaryResponse.class)
+public interface ContestantAnswerSummaryResponse {
+    BasicProfile getProfile();
```
Comment (fushar) [inline judgels-backends/uriel/uriel-api/src/main/java/judgels/uriel/api/contest/submission/bundle/ContestantAnswerSummaryResponse.java]: Why basic? This should be `Profile`, like everything else, so that user rating is also returned.

File: judgels-backends/sandalphon/sandalphon-client/src/main/java/judgels/sandalphon/problem/ProblemClient.java [hunk 2]
```diff
@@ -0,0 +1,147 @@
...
+
+    public Optional<Item> getItem(String problemJid, String itemJid) {
+        judgels.sandalphon.api.problem.bundle.ProblemWorksheet
+                worksheet = getBundleProblemWorksheet(problemJid, Optional.empty());
+        return worksheet.getItems().stream()
+                .filter(item -> itemJid.equals(item.getJid()))
+                .findAny();
+    }
+
+    public Map<String, String> getItemMetaByItemJid(Set<String> problemJids) {
```
Comment (fushar) [inline judgels-backends/sandalphon/sandalphon-client/src/main/java/judgels/sandalphon/problem/ProblemClient.java]: Unused method?

File: judgels-backends/sandalphon/sandalphon-client/src/main/java/judgels/sandalphon/problem/ProblemClient.java [hunk 3]
```diff
@@ -0,0 +1,147 @@
...
+        this.itemProcessorRegistry = itemProcessorRegistry;
+    }
+
+    public Map<String, String> translateAllowedSlugsToProblemJids(String actorJid, Set<String> slugs) {
+        return slugs.isEmpty()
+                ? ImmutableMap.of()
+                : clientProblemService.translateAllowedSlugsToJids(sandalphonClientAuthHeader, actorJid, slugs);
+    }
+
+    public ProblemInfo getProblemInfo(String problemJid) {
```
Comment (fushar) [inline judgels-backends/sandalphon/sandalphon-client/src/main/java/judgels/sandalphon/problem/ProblemClient.java]:
```suggestion
    public ProblemInfo getProblem(String problemJid) {
```

File: judgels-backends/sandalphon/sandalphon-client/src/main/java/judgels/sandalphon/problem/ProblemClient.java [hunk 4]
```diff
@@ -0,0 +1,147 @@
...
+        return clientProblemService.getProblem(sandalphonClientAuthHeader, problemJid);
+    }
+
+    public Map<String, ProblemInfo> getProblemInfoByProblemJid(Set<String> problemJids) {
```
Comment (fushar) [inline judgels-backends/sandalphon/sandalphon-client/src/main/java/judgels/sandalphon/problem/ProblemClient.java]:
```suggestion
    public Map<String, ProblemInfo> getProblems(Set<String> problemJids) {
```

File: judgels-backends/sandalphon/sandalphon-client/src/main/java/judgels/sandalphon/problem/ProblemClient.java [hunk 5]
```diff
@@ -0,0 +1,147 @@
...
+        return problemJids.isEmpty()
+                ? ImmutableMap.of()
+                : clientProblemService.getProblems(sandalphonClientAuthHeader, problemJids);
+    }
+
+    public Map<String, String> getProblemNamesByProblemJid(Set<String> problemJids, Optional<String> language) {
```
Comment (fushar) [inline judgels-backends/sandalphon/sandalphon-client/src/main/java/judgels/sandalphon/problem/ProblemClient.java]:
```suggestion
    public Map<String, String> getProblemNames(Set<String> problemJids, Optional<String> language) {
```

File: judgels-backends/sandalphon/sandalphon-client/src/main/java/judgels/sandalphon/problem/ProblemClient.java [hunk 6]
```diff
@@ -0,0 +1,147 @@
...
+            ClientProblemService clientProblemService,
+            ItemProcessorRegistry itemProcessorRegistry) {
+
+        this.sandalphonConfig = sandalphonConfig;
+        this.sandalphonClientAuthHeader = sandalphonClientAuthHeader;
+        this.clientProblemService = clientProblemService;
+        this.itemProcessorRegistry = itemProcessorRegistry;
+    }
+
+    public Map<String, String> translateAllowedSlugsToProblemJids(String actorJid, Set<String> slugs) {
```
Comment (fushar) [inline judgels-backends/sandalphon/sandalphon-client/src/main/java/judgels/sandalphon/problem/ProblemClient.java]:
```suggestion
    public Map<String, String> translateAllowedSlugsToJids(String actorJid, Set<String> slugs) {
```

File: judgels-backends/sandalphon/sandalphon-client/src/main/java/judgels/sandalphon/problem/ProblemClient.java [hunk 7]
```diff
@@ -0,0 +1,147 @@
...
+import judgels.sandalphon.api.client.problem.ClientProblemService;
+import judgels.sandalphon.api.problem.ProblemInfo;
+import judgels.sandalphon.api.problem.ProblemStatement;
+import judgels.sandalphon.api.problem.bundle.Item;
+import judgels.sandalphon.api.problem.programming.ProblemSubmissionConfig;
+import judgels.sandalphon.api.problem.programming.ProblemWorksheet;
+import judgels.sandalphon.problem.bundle.ItemProcessorRegistry;
+import judgels.service.api.client.BasicAuthHeader;
+
+public class ProblemClient {
```
Comment (fushar) [inline judgels-backends/sandalphon/sandalphon-client/src/main/java/judgels/sandalphon/problem/ProblemClient.java:22]: Because the context here is clear ("problem"), I'm suggesting to remove redundant "problemJid" in method names as follows.

File: judgels-backends/uriel/uriel-app/src/main/java/judgels/uriel/contest/submission/bundle/ContestItemSubmissionResource.java [hunk 8]
```diff
@@ -235,22 +249,63 @@ public ContestantAnswersResponse getLatestContestantAnswersInContest(
...
+                    .filter(item -> !item.getType().equals(ItemType.STATEMENT))
+                    .collect(Collectors.toList());
+            items.sort(Comparator.comparingInt(item -> item.getNumber().orElse(0)));
+
+            List<ItemSubmission> problemSubmissions = new ArrayList<>();
+            for (Item item : items) {
+                problemSubmissions.add(submissionsByItemJid.computeIfAbsent(
+                        item.getJid(),
+                        itemJid -> new ItemSubmission.Builder()
+                                .jid("")
```
Comment (fushar) [inline judgels-backends/uriel/uriel-app/src/main/java/judgels/uriel/contest/submission/bundle/ContestItemSubmissionResource.java]: So many empty strings here?

File: judgels-backends/uriel/uriel-api/src/main/java/judgels/uriel/api/contest/submission/bundle/ContestantAnswerSummaryResponse.java [hunk 9]
```diff
@@ -0,0 +1,22 @@
...
+    ContestSubmissionConfig getConfig();
+    Map<String, List<ItemSubmission>> getSubmissionsByProblemJid();
```
Comment (fushar) [inline judgels-backends/uriel/uriel-api/src/main/java/judgels/uriel/api/contest/submission/bundle/ContestantAnswerSummaryResponse.java]: Can we follow the convention used in everywhere else?

```
getSubmissionsMap()
getProblemAliasesMap()
getProblemNamesMap()
getItemNumbersMap()
```

**Review by fushar — CHANGES_REQUESTED** [review]

File: judgels-backends/uriel/uriel-api/src/main/java/judgels/uriel/api/contest/submission/bundle/ContestantAnswerSummaryResponse.java (hunk 1 above)
Comment (nathanchrs) [reply judgels-backends/uriel/uriel-api/src/main/java/judgels/uriel/api/contest/submission/bundle/ContestantAnswerSummaryResponse.java]: BasicProfile contains username, name, rating, and country already

Comment (nathanchrs) [reply judgels-backends/uriel/uriel-api/src/main/java/judgels/uriel/api/contest/submission/bundle/ContestantAnswerSummaryResponse.java]: ... just realized Profile contains username, rating and country. Will be changed to Profile.

File: judgels-backends/sandalphon/sandalphon-client/src/main/java/judgels/sandalphon/problem/ProblemClient.java (hunk 6 above)
Comment (nathanchrs) [reply judgels-backends/sandalphon/sandalphon-client/src/main/java/judgels/sandalphon/problem/ProblemClient.java]: Changed

File: judgels-backends/sandalphon/sandalphon-client/src/main/java/judgels/sandalphon/problem/ProblemClient.java (hunk 5 above)
Comment (nathanchrs) [reply judgels-backends/sandalphon/sandalphon-client/src/main/java/judgels/sandalphon/problem/ProblemClient.java]: Changed

File: judgels-backends/sandalphon/sandalphon-client/src/main/java/judgels/sandalphon/problem/ProblemClient.java (hunk 7 above)
Comment (nathanchrs) [reply judgels-backends/sandalphon/sandalphon-client/src/main/java/judgels/sandalphon/problem/ProblemClient.java:22]: OK

File: judgels-backends/sandalphon/sandalphon-client/src/main/java/judgels/sandalphon/problem/ProblemClient.java (hunk 4 above)
Comment (nathanchrs) [reply judgels-backends/sandalphon/sandalphon-client/src/main/java/judgels/sandalphon/problem/ProblemClient.java]: Changed

File: judgels-backends/sandalphon/sandalphon-client/src/main/java/judgels/sandalphon/problem/ProblemClient.java (hunk 3 above)
Comment (nathanchrs) [reply judgels-backends/sandalphon/sandalphon-client/src/main/java/judgels/sandalphon/problem/ProblemClient.java]: Changed

File: judgels-backends/sandalphon/sandalphon-client/src/main/java/judgels/sandalphon/problem/ProblemClient.java (hunk 2 above)
Comment (nathanchrs) [reply judgels-backends/sandalphon/sandalphon-client/src/main/java/judgels/sandalphon/problem/ProblemClient.java]: Removed

File: judgels-backends/uriel/uriel-app/src/main/java/judgels/uriel/contest/submission/bundle/ContestItemSubmissionResource.java (hunk 8 above)
Comment (nathanchrs) [reply judgels-backends/uriel/uriel-app/src/main/java/judgels/uriel/contest/submission/bundle/ContestItemSubmissionResource.java]: For dummy item; `ContestantAnswerSummaryResponse` will be changed according to the new format (
```
    Profile getProfile();
    ContestSubmissionConfig getConfig();
    Map<String, List<String>> getItemJidsByProblemJid();
    Map<String, ItemSubmission> getSubmissionsByItemJid();
    Map<String, String> getProblemAliasesMap();
    Map<String, String> getProblemNamesMap();
```
)

File: judgels-backends/uriel/uriel-api/src/main/java/judgels/uriel/api/contest/submission/bundle/ContestantAnswerSummaryResponse.java (hunk 9 above)
Comment (nathanchrs) [reply judgels-backends/uriel/uriel-api/src/main/java/judgels/uriel/api/contest/submission/bundle/ContestantAnswerSummaryResponse.java]: Will be changed to the new format

File: judgels-backends/uriel/uriel-app/src/integTest/java/judgels/uriel/api/mocks/MockJophiel.java [hunk 10]
```diff
@@ -137,6 +137,14 @@ public static WireMockServer mockJophiel() {
         mockJophiel.stubFor(post(urlPathEqualTo("/api/v2/profiles/"))
                 .willReturn(aResponse().withStatus(200).withTransformers("get-profiles")));
 
+        mockJophiel.stubFor(get("/api/v2/profiles/" + CONTESTANT_JID + "/basic")
```
Comment (fushar) [inline judgels-backends/uriel/uriel-app/src/integTest/java/judgels/uriel/api/mocks/MockJophiel.java]: This is unused anymore

File: judgels-backends/uriel/uriel-app/src/main/java/judgels/uriel/contest/submission/bundle/ContestItemSubmissionResource.java [hunk 11]
```diff
@@ -235,22 +246,49 @@ public ContestantAnswersResponse getLatestContestantAnswersInContest(
...
-                .userJids(userJids)
-                .problemJids(problemJids)
+                .userJids(ImmutableList.of(viewedUserJid))
+                .problemJids(bundleProblemJidsSortedByAlias)
                 .build();
 
-        Map<String, String> problemAliasesMap = problemStore.getProblemAliasesByJids(contest.getJid(), problemJids);
-
-        return new ContestantAnswersResponse.Builder()
-                .answers(submissions.stream().collect(Collectors.groupingBy(ItemSubmission::getProblemJid)))
```
Comment (fushar) [inline judgels-backends/uriel/uriel-app/src/main/java/judgels/uriel/contest/submission/bundle/ContestItemSubmissionResource.java:251]: Will require changes in Raphael, or else it will break

**Review by fushar — CHANGES_REQUESTED** [review]

File: judgels-backends/uriel/uriel-app/src/integTest/java/judgels/uriel/api/mocks/MockJophiel.java (hunk 10 above)
Comment (nathanchrs) [reply judgels-backends/uriel/uriel-app/src/integTest/java/judgels/uriel/api/mocks/MockJophiel.java]: Removed

**Review by fushar — APPROVED** [review]

**Review by fushar — APPROVED** [review]

File: judgels-frontends/raphael/src/routes/uriel/contests/single/submissions/Bundle/modules/contestSubmissionActions.ts [hunk 12]
```diff
@@ -23,14 +23,14 @@ export const contestSubmissionActions = {
...
+  getSummary: (contestJid: string, userJid?: string, language?: string) => {
     return async (dispatch, getState, { contestSubmissionBundleAPI }) => {
       const token = selectToken(getState());
-      return contestSubmissionBundleAPI.getLatestContestantAnswersInContest(token, contestJid, userJid);
+      return contestSubmissionBundleAPI.getAnswerSummaryForContestant(token, contestJid, userJid, language);
     };
   },
 
-  getLatestSubmission: (contestJid: string, problemJid: string) => {
+  getLatestSubmissions: (contestJid: string, problemJid: string) => {
```
Comment (jauhararifin) [inline judgels-frontends/raphael/src/routes/uriel/contests/single/submissions/Bundle/modules/contestSubmissionActions.ts:33]: Actually you have to change [ContestProblemPage.tsx at line 140](https://github.com/ia-toki/judgels/blob/3c8a6e84424d7a12e315558dba8b119d791b38cd/judgels-frontends/raphael/src/routes/uriel/contests/single/problems/single/ContestProblemPage/Bundle/ContestProblemPage.tsx#L140) too

Comment (fushar) [reply judgels-frontends/raphael/src/routes/uriel/contests/single/submissions/Bundle/modules/contestSubmissionActions.ts:33]: Oh, right. Can you fix it? :')
