### PR TITLE
fix: last modified at field after uploading files

### LINKED ISSUE #540: [Bug] All files 'Last modified at' field shows 'just now' after uploading files
After uploading files, all files' 'Last Modified At' field becomes 'Just Now,' but when this change is committed, the field becomes in accordance

Before commit:
image

After commit:
image

### PR DESCRIPTION
**Pull request by kadeksuryam**
Resolve #540

**Root Cause:**
Git [doesn't actually record timestamps for files](https://stackoverflow.com/questions/2179722/checking-out-old-files-with-original-create-modified-timestamps/2179825#2179825). Consequently, when a repository is cloned, the timestamp becomes the current time.

**Solution:**
Rather than using the git clone API, I utilize the filesystem API to recursively copy one git directory to another and subsequently set the origin URI.

### CODE REVIEW

File: judgels-backends/judgels-commons/judgels-fs/src/main/java/judgels/fs/FileSystem.java [hunk 1]
```diff
@@ -28,4 +28,7 @@ default void writeToFile(Path filePath, String content) {
     default String readFromFile(Path filePath) {
         return new String(readByteArrayFromFile(filePath));
     }
+
+    void copyDirectory(Path src, Path dest);
+    void copy(Path src, Path dest);
```
Comment (fushar) [inline judgels-backends/judgels-commons/judgels-fs/src/main/java/judgels/fs/FileSystem.java:33]: Looks like this new `copy()` method is not used in this PR.

File: judgels-backends/judgels-commons/judgels-fs/src/main/java/judgels/fs/FileSystem.java [hunk 2]
```diff
@@ -28,4 +28,7 @@ default void writeToFile(Path filePath, String content) {
     default String readFromFile(Path filePath) {
         return new String(readByteArrayFromFile(filePath));
     }
+
+    void copyDirectory(Path src, Path dest);
```
Comment (fushar) [inline judgels-backends/judgels-commons/judgels-fs/src/main/java/judgels/fs/FileSystem.java:32]: Can we move this method a bit up? Wanted to keep all the default methods to be the last.

File: judgels-backends/judgels-server-app/src/main/java/judgels/sandalphon/LocalGit.java [hunk 3]
```diff
@@ -88,12 +94,20 @@ public void addAll(Path rootDirPath) {
     }
 
     @Override
-    public void commit(Path rootDirPath, String committerName, String committerEmail, String title, String description) {
+    public void commit(
```
Comment (fushar) [inline judgels-backends/judgels-server-app/src/main/java/judgels/sandalphon/LocalGit.java:97]: Can we revert all formatting changes in this file that are not related to the PR? It is a bit confusing 😄

**Review by fushar — CHANGES_REQUESTED** [review]
@kadeksuryam Thanks for the contribution! The idea is solid. Left some comments.

File: judgels-backends/judgels-commons/judgels-fs/src/main/java/judgels/fs/FileSystem.java (hunk 1 above)
Comment (fushar) [reply judgels-backends/judgels-commons/judgels-fs/src/main/java/judgels/fs/FileSystem.java:33]: Oh, I missed the usage, please ignore :)

File: judgels-backends/judgels-commons/judgels-fs/src/main/java/judgels/fs/local/LocalFileSystem.java [hunk 4]
```diff
@@ -213,4 +217,22 @@ public byte[] readByteArrayFromFile(Path filePath) {
             throw new RuntimeException(e);
         }
     }
+
+    @Override
+    public void copyDirectory(Path src, Path dest) {
+        try (Stream<Path> stream = Files.walk(src)) {
```
Comment (fushar) [inline judgels-backends/judgels-commons/judgels-fs/src/main/java/judgels/fs/local/LocalFileSystem.java:223]: I think we can simply use something like `FileUtils.copyDirectory()`?

**Review by fushar — APPROVED** [review]
Merging. No responses but the changes are good enough :)
