### PR TITLE
Fix grading config leak in Uriel bundle problem worksheet endpoint

### LINKED ISSUE #127: Uriel bundle problem worksheet endpoint leaks grading info
**Expected:** response for Uriel bundle problem worksheet endpoint should not include grading info (e.g. `isCorrect` for multiple choice items), except if accessed by a manager or admin.
**Actual:** response contains grading info.

### PR DESCRIPTION
**Pull request by nathanchrs**
Fixes #127.

- [x] Move parsing of item config JSON from Uriel to Sandalphon legacy since Uriel needs to understand the contents of item config anyway to remove its grading config
- [x] Add integration tests for the bundle problem worksheet endpoint in Uriel
- [x] Fix the grading config leak: now only manager/admin gets the grading config (`isCorrect`, etc.) when requesting a bundle problem worksheet

### CODE REVIEW

**Comment by GilangJS** [comment]
Please attach issue id.
Also use issue id for next commit messages.

File: judgels-legacy/sandalphon/app/org/iatoki/judgels/sandalphon/controllers/api/client/v2/ClientProblemAPIControllerV2.java [hunk 1]
```diff
@@ -134,13 +137,18 @@ public Result getBundleProblemWorksheet(String problemJid) {
             List<BundleItem> items = bundleItemService.getBundleItemsInProblemWithClone(problemJid, null);
             List<Item> itemsWithConfig = new ArrayList<>();
             for (BundleItem item : items) {
-                String itemConfig = bundleItemService.getItemConfInProblemWithCloneByJid(
+                String itemConfigString = bundleItemService.getItemConfInProblemWithCloneByJid(
                         problemJid, null, item.getJid(), language);
+                ItemType type = ItemType.valueOf(item.getType().name());
+
+                ObjectMapper objectMapper = new ObjectMapper();
```
Comment (fushar) [inline judgels-legacy/sandalphon/app/org/iatoki/judgels/sandalphon/controllers/api/client/v2/ClientProblemAPIControllerV2.java]: Please put this as a static final field in this class, so that it is only instantiated once

File: judgels-backends/sandalphon/sandalphon-api/src/main/java/judgels/sandalphon/api/problem/bundle/Item.java [hunk 2]
```diff
@@ -9,7 +12,25 @@
...
+            property = "type",
+            visible = true
+    )
+    @JsonSubTypes({
+            @JsonSubTypes.Type(value = ImmutableStatementItemConfig.class, name = ItemType.Statement),
+            @JsonSubTypes.Type(value = ImmutableMultipleChoiceItemConfig.class, name = ItemType.MultipleChoice)
+    })
+    ItemConfig getConfig();
+
+    default Item processDisplayText(Function<String, String> processor) {
```
Comment (fushar) [inline judgels-backends/sandalphon/sandalphon-api/src/main/java/judgels/sandalphon/api/problem/bundle/Item.java]: This can be removed, to minimize logic in a POJO. We can do this in the resource class instead. (Like what you do for `withoutGradingInfo()`

File: judgels-backends/sandalphon/sandalphon-api/src/main/java/judgels/sandalphon/api/problem/bundle/ItemConfig.java [hunk 3]
```diff
@@ -1,5 +1,21 @@
...
+import com.fasterxml.jackson.databind.ObjectMapper;
+import java.io.IOException;
+import java.util.function.Function;
+
 public interface ItemConfig {
     String getStatement();
+    ItemConfig processDisplayText(Function<String, String> processor);
+    ItemConfig withoutGradingInfo();
+
+    static ItemConfig fromString(ObjectMapper objectMapper, ItemType itemType, String string) throws IOException {
```
Comment (fushar) [inline judgels-backends/sandalphon/sandalphon-api/src/main/java/judgels/sandalphon/api/problem/bundle/ItemConfig.java]: Move this to the resource class (at least for now).

File: judgels-backends/sandalphon/sandalphon-api/src/main/java/judgels/sandalphon/api/problem/bundle/ItemConfig.java [hunk 4]
```diff
@@ -1,5 +1,21 @@
 package judgels.sandalphon.api.problem.bundle;
 
+import com.fasterxml.jackson.databind.ObjectMapper;
+import java.io.IOException;
+import java.util.function.Function;
+
 public interface ItemConfig {
     String getStatement();
+    ItemConfig processDisplayText(Function<String, String> processor);
```
Comment (fushar) [inline judgels-backends/sandalphon/sandalphon-api/src/main/java/judgels/sandalphon/api/problem/bundle/ItemConfig.java]: The more canonical name is:

```suggestion
    ItemConfig transformContentText(Function<String, String> transformer);
```

(display -> content to be specific, because for example "alias" is also a displayed text but is not actually transformed)

File: judgels-backends/sandalphon/sandalphon-api/src/main/java/judgels/sandalphon/api/problem/bundle/ItemType.java [hunk 5]
```diff
@@ -1,6 +1,9 @@
 package judgels.sandalphon.api.problem.bundle;
 
 public enum ItemType {
-    STATEMENT,
-    MULTIPLE_CHOICE
+    STATEMENT, MULTIPLE_CHOICE;
+
+    // String constants for use in annotations (evaluated at compile-time)
+    static final String Statement = "STATEMENT";
```
Comment (fushar) [inline judgels-backends/sandalphon/sandalphon-api/src/main/java/judgels/sandalphon/api/problem/bundle/ItemType.java]: This violates naming convention for constants (all uppercase).

I suggest to just hardcode the constants in `@JsonSubTypes`. It's clear enough and we only have 2 anyway.

File: judgels-backends/uriel/uriel-app/src/main/java/judgels/uriel/contest/problem/ContestProblemResource.java [hunk 6]
```diff
@@ -218,6 +222,8 @@ public ContestProblemWorksheet getBundleProblemWorksheet(
         String problemJid = problem.getProblemJid();
         ProblemInfo problemInfo = clientProblemService.getProblem(sandalphonClientAuthHeader, problemJid);
 
+        boolean canManage = problemRoleChecker.canManage(actorJid, contest);
```
Comment (fushar) [inline judgels-backends/uriel/uriel-app/src/main/java/judgels/uriel/contest/problem/ContestProblemResource.java]: Actually, I think this check is not required at all. We can just always return the items without grading info from uriel. Even managers need not that info. If that info is required, it should be fetched from the source of truth (sandalphon), not via Uriel.

File: judgels-backends/sandalphon/sandalphon-api/src/main/java/judgels/sandalphon/api/problem/bundle/ItemConfig.java [hunk 7]
```diff
@@ -1,5 +1,21 @@
...
+    ItemConfig withoutGradingInfo();
```
Comment (fushar) [inline judgels-backends/sandalphon/sandalphon-api/src/main/java/judgels/sandalphon/api/problem/bundle/ItemConfig.java]: I think the correct name is actually `withoutAnswerKey()`. Because "grading" info should also include e.g. penalty and score, which is not excluded here.

**Review by fushar — CHANGES_REQUESTED** [review]

File: judgels-legacy/sandalphon/app/org/iatoki/judgels/sandalphon/controllers/api/client/v2/ClientProblemAPIControllerV2.java (hunk 1 above)
Comment (nathanchrs) [reply judgels-legacy/sandalphon/app/org/iatoki/judgels/sandalphon/controllers/api/client/v2/ClientProblemAPIControllerV2.java]: fixed to use final class field (non-static as we need to register a module to the objectMapper before use)

Comment (fushar) [reply judgels-legacy/sandalphon/app/org/iatoki/judgels/sandalphon/controllers/api/client/v2/ClientProblemAPIControllerV2.java]:
```
private static final ObjectMapper MAPPER = new ObjectMapper().registerModule(new Jdk8Module());
```

File: judgels-backends/sandalphon/sandalphon-api/src/main/java/judgels/sandalphon/api/problem/bundle/ItemConfig.java (hunk 4 above)
Comment (nathanchrs) [reply judgels-backends/sandalphon/sandalphon-api/src/main/java/judgels/sandalphon/api/problem/bundle/ItemConfig.java]: Renamed

File: judgels-backends/sandalphon/sandalphon-api/src/main/java/judgels/sandalphon/api/problem/bundle/ItemType.java (hunk 5 above)
Comment (nathanchrs) [reply judgels-backends/sandalphon/sandalphon-api/src/main/java/judgels/sandalphon/api/problem/bundle/ItemType.java]: Changed

File: judgels-backends/uriel/uriel-app/src/main/java/judgels/uriel/contest/problem/ContestProblemResource.java (hunk 6 above)
Comment (nathanchrs) [reply judgels-backends/uriel/uriel-app/src/main/java/judgels/uriel/contest/problem/ContestProblemResource.java]: Changed

File: judgels-backends/sandalphon/sandalphon-api/src/main/java/judgels/sandalphon/api/problem/bundle/Item.java (hunk 2 above)
Comment (nathanchrs) [reply judgels-backends/sandalphon/sandalphon-api/src/main/java/judgels/sandalphon/api/problem/bundle/Item.java]: Replaced with Processor pattern (like in `ScoreboardProcessor`)

File: judgels-backends/sandalphon/sandalphon-api/src/main/java/judgels/sandalphon/api/problem/bundle/ItemConfig.java (hunk 3 above)
Comment (nathanchrs) [reply judgels-backends/sandalphon/sandalphon-api/src/main/java/judgels/sandalphon/api/problem/bundle/ItemConfig.java]: Replaced with Processor pattern (like in `ScoreboardProcessor`)

File: judgels-backends/sandalphon/sandalphon-api/src/main/java/judgels/sandalphon/api/problem/bundle/ItemConfig.java (hunk 7 above)
Comment (nathanchrs) [reply judgels-backends/sandalphon/sandalphon-api/src/main/java/judgels/sandalphon/api/problem/bundle/ItemConfig.java]: Changed

**Review by fushar — APPROVED** [review]
