### PR TITLE
Fix unfiltered submissions on the first view

### LINKED ISSUE #248: Submissions not filtered
Go to https://tlx.toki.id/contests/troc-10-div-2/submissions?problemAlias=A

submissions are not filtered by problem A, but going to page two by clicking on the next page, submissions became filtered

### PR DESCRIPTION
**Pull request by yonasadiel**
Resolves #248.

Uriel only provides API for fetching submissions by problem JID, not alias. However,  raphael use problem alias on the url params. Thus, we need to fetch the problems first (including all submissions, unfiltered).

In the original code, submissions are fetched on `componentDidMount` and filtered by `react-paginate`. However, these two tasks are asynchronous, so the filter is not working on the first view, but working when someone open other page.

To handle this, I move the submissions fetching to `componentDidUpdate`, when problem list has already been fetched, but not filtered. Then, we call `refreshSubmissions` to get the matched problem JID.

However, user will be given list of submissions unfiltered first, because we have the unfiltered list. The filter loading is on, so it shows that the filter is still working.
loading

Then, the filtered list shown.
done

### CODE REVIEW

File: judgels-frontends/raphael/src/routes/contests/contests/single/submissions/Programming/ContestSubmissionsPage/ContestSubmissionsPage.tsx [hunk 1]
```diff
@@ -59,10 +59,14 @@ export class ContestSubmissionsPage extends React.PureComponent<
...
-    if (filter.username || filter.problemAlias) {
-      await this.refreshSubmissions();
+  async componentDidUpdate(prevProps: ContestSubmissionsPageProps, prevState: ContestSubmissionsPageState) {
+    const {
+      response,
+      filter: { username, problemAlias },
+    } = this.state;
+    if (!prevState.response && response && (username || problemAlias)) {
+      this.setState({ isFilterLoading: true });
+      this.refreshSubmissions(username, problemAlias);
```
Comment (fushar) [inline judgels-frontends/raphael/src/routes/contests/contests/single/submissions/Programming/ContestSubmissionsPage/ContestSubmissionsPage.tsx]:
```suggestion
      await this.refreshSubmissions(username, problemAlias);
```

**Review by fushar — CHANGES_REQUESTED** [review]

File: judgels-frontends/raphael/src/routes/contests/contests/single/submissions/Programming/ContestSubmissionsPage/ContestSubmissionsPage.tsx (hunk 1 above)
Comment (yonasadiel) [reply judgels-frontends/raphael/src/routes/contests/contests/single/submissions/Programming/ContestSubmissionsPage/ContestSubmissionsPage.tsx]: But why? Isn't the `await` will block the function call? I think it is doesn't matter to be blocking or not?

Comment (fushar) [reply judgels-frontends/raphael/src/routes/contests/contests/single/submissions/Programming/ContestSubmissionsPage/ContestSubmissionsPage.tsx]: Either add the `await`, or remove `async` from the function declaration.

**Review by fushar — APPROVED** [review]
